version: '3.1'

volumes:
  database:

networks:
  web:

services:
  db:
    image: postgres:12-alpine
    restart: 'no'
    volumes:
      - database:/var/lib/postgressql/data:z
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - web
    ports:
      - "5432:5432"